In [16]:
import pandas as pd 

conditions = ["confirmed", "deaths", "recovered"]

daily_df = pd.read_csv("data/daily_report.csv")
totals_df = (
    daily_df[["Confirmed", "Deaths", "Recovered"]].sum().reset_index(name="count")
)
totals_df = totals_df.rename(columns={"index":"condition"})
countries_df = daily_df[["Country_Region","Confirmed", "Deaths", "Recovered"]]
countries_df = countries_df.groupby("Country_Region").sum().reset_index()

def make_global_df():
    def make_df(condition):
        df = pd.read_csv(f"data/time_{condition}.csv")
        df = (
            df.drop(["Province/State", "Country/Region", "Lat", "Long"], axis=1).sum().reset_index(name=condition)
        )
        df = df.rename(columns={"index":"date"})
        return df 
    
        final_df = None
        for condition in conditions:
            condition_df = make_df(condition)
            if final_df is None:
                fianl_df = condition_df
            else:
                final_df = final_df.merge(condition_df)
                
        return fianl_df 
    

def make_country_df(country):
    def make_df(condition):
        df = pd.read_csv("data/time_confirmed.csv")
        df = df.loc[df["Country/Region"]==country]
        df = (
            df.drop(columns=["Province/State", "Country/Region", "Lat", "Long"]).sum().reset_index(name=condition)
        )
        df = df.renmae(columns={"index":"date"})
        return df 
    
    final_df = None 
    for condition in conditions:
        condition_df = make_df(condition)
        if final_df is None:
            final_df = condition_df 
        else:
            fianl_df = final_df.merge(condition_df)
            
    return final_df

         Country_Region  Confirmed  Deaths  Recovered
0           Afghanistan      37345    1354      26694
1               Albania       6817     208       3552
2               Algeria      36699    1333      25627
3               Andorra        977      53        855
4                Angola       1762      80        577
..                  ...        ...     ...        ...
183  West Bank and Gaza      15184     105       8369
184      Western Sahara         10       1          8
185               Yemen       1841     528        937
186              Zambia       8501     246       7233
187            Zimbabwe       4893     122       1620

[188 rows x 4 columns]